### PR TITLE
fixed view  for database entry

### PR DESCRIPTION
**Pull request by arpit-jaswani**

### CODE REVIEW

**Comment by jenniferabowd** [comment]
Thank you so much! How did you find this repo? At one point I had that working!

**Comment by arpitjaswani** [comment]
welcome!! I have looking around some socket stuff, came across your repo and fixed!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arpitjaswani** [comment]
welcome! I have been looking around some socket stuff, came across your repo and fixed!
yes, you have done it almost.
thanks for accepting! it's my first github  👍

**Comment by arpit-jaswani** [comment]
welcome! I have been looking around some socket stuff, came across your repo and fixed!
yes, you have done it almost.
thanks for accepting! it's my first github contribution 👍

**Pull request merged**
